### ISSUE TITLE
Grid mismatch

### ISSUE THREAD

**Issue by caumond** [bfn-yazilim/queens#2]
I have selected grid #3 and played. 
But it printed grid 203, and when I have solved it:

<img width="479" alt="image" src="https://github.com/user-attachments/assets/f416bd17-c2e4-4687-8878-0f22eeefcc03" />

It was not accepted.

When I did the same with grid #2, I have solved it, and then it have leaped to 201.&

**Comment by sooneer** [comment]
Hello, I saw the problem and I just fixed it. Can you check please? Thank you.

**Comment by caumond** [comment]
Yeas, solved !
